### ISSUE TITLE
Publish Docker image to Docker Hub

### ISSUE THREAD

**Issue by maxlerebourg** [ynuwenhof/koblas#3]
Hello, I wan't to try your proxy but you don't provide docker image. Could you do it ? In a CI ?

**Comment by ynuwenhof** [comment]
Hey, I have built and published the latest Docker image to the [Docker Hub](https://hub.docker.com/r/ynuwenhof/koblas), you can pull the image with `docker pull ynuwenhof/koblas:latest`. I will update the Project README and set up a CI soon.
